import { useState } from 'react';
import { Microscope, Search, BookOpen, ExternalLink, ChevronRight, Sparkles, TrendingUp, Globe } from 'lucide-react';
import { simulateResearch, researchTopics } from '../utils/deepResearch';
import { ResearchTopic, ActivityItem } from '../types';
interface Props { addActivity: (a: Omit<ActivityItem, 'id' | 'timestamp'>) => void }
export default function DeepResearch({ addActivity }: Props) {
  const [q, setQ] = useState(''); const [loading, setLoading] = useState(false); const [result, setResult] = useState<ResearchTopic | null>(null);
  const handleResearch = (topic?: string) => { const t = topic || q; if (!t.trim()) return; setLoading(true); setResult(null); setTimeout(() => { const r = simulateResearch(t); setResult(r); setLoading(false); addActivity({ type: 'research-completed', title: `Researched: ${t.slice(0, 40)}`, description: `${r.sources.length} sources analyzed` }); }, 2500); };
  return (<div className="space-y-6 animate-fade-in"><div><h1 className="text-2xl font-bold text-white flex items-center gap-2"><Microscope size={24} className="text-orange-400" /> Deep Research</h1><p className="text-gray-400 mt-1 text-sm">Multi-source security analysis with sourced insights and actionable recommendations</p></div>
    <div className="bg-[#0d0d18] border border-gray-800/40 rounded-xl p-5 animate-slide-up"><label className="block text-sm font-medium text-gray-300 mb-2 flex items-center gap-2"><Search size={14} className="text-orange-400" /> Research Topic</label><div className="flex gap-2"><input value={q} onChange={e => setQ(e.target.value)} onKeyDown={e => e.key === 'Enter' && handleResearch()} placeholder="Enter a security topic..." className="flex-1 bg-[#0a0a14] border border-gray-700/40 rounded-lg px-4 py-3 text-sm text-gray-200 placeholder-gray-600 focus:outline-none focus:border-orange-500/50" /><button onClick={() => handleResearch()} disabled={!q.trim() || loading} className="px-5 py-3 rounded-lg bg-gradient-to-r from-orange-500 to-red-500 hover:from-orange-600 hover:to-red-600 disabled:from-gray-700 disabled:to-gray-700 disabled:text-gray-500 text-white text-sm shadow-lg shadow-orange-500/15 disabled:shadow-none flex items-center gap-2">{loading ? <><div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" /> Researching...</> : <><Microscope size={16} /> Research</>}</button></div></div>
    <div className="animate-slide-up" style={{ animationDelay: '80ms' }}><h3 className="text-xs font-medium text-gray-400 mb-2">Suggested Topics</h3><div className="flex flex-wrap gap-2">{researchTopics.map(t => <button key={t} onClick={() => { setQ(t); handleResearch(t); }} className="px-3 py-1.5 rounded-full bg-gray-800/30 border border-gray-700/20 text-[11px] text-gray-400 hover:text-orange-400 hover:border-orange-500/25 flex items-center gap-1.5"><ChevronRight size={10} />{t}</button>)}</div></div>
    {loading && <div className="bg-[#0d0d18] border border-gray-800/40 rounded-xl p-8 animate-fade-in"><div className="flex items-center gap-3 mb-6"><div className="w-10 h-10 rounded-xl bg-orange-500/10 flex items-center justify-center"><Microscope size={20} className="text-orange-400 animate-pulse" /></div><div><h3 className="text-sm font-semibold text-white">Researching: {q}</h3><p className="text-xs text-gray-500">Analyzing multiple sources...</p></div></div><div className="space-y-3">{['Querying security databases', 'Analyzing framework documentation', 'Cross-referencing threat intelligence', 'Compiling findings'].map((s, i) => <div key={i} className="flex items-center gap-3 animate-slide-up" style={{ animationDelay: `${i * 600}ms` }}><div className={`w-5 h-5 rounded-full flex items-center justify-center text-[10px] ${i < 2 ? 'bg-emerald-500/20 text-emerald-400' : 'bg-gray-800 text-gray-500'}`}>{i < 2 ? '✓' : '...'}</div><span className={`text-xs ${i < 2 ? 'text-gray-300' : 'text-gray-500'}`}>{s}</span></div>)}</div></div>}
    {result && !loading && <div className="space-y-4 animate-fade-in">
      <div className="bg-gradient-to-r from-orange-500/5 via-red-500/5 to-purple-500/5 border border-gray-800/40 rounded-xl p-6"><div className="flex items-start gap-4"><div className="w-10 h-10 rounded-xl bg-orange-500/10 flex items-center justify-center shrink-0"><TrendingUp size={20} className="text-orange-400" /></div><div><h3 className="text-base font-semibold text-white mb-2">Executive Summary</h3><p className="text-sm text-gray-300 leading-relaxed">{result.summary}</p></div></div></div>
      {result.sections.map((sec, i) => <div key={i} className="bg-[#0d0d18] border border-gray-800/40 rounded-xl p-6 animate-slide-up" style={{ animationDelay: `${i * 100}ms` }}><h3 className="text-base font-semibold text-white mb-3 flex items-center gap-2"><BookOpen size={15} className="text-orange-400" />{sec.title}</h3><div className="text-sm text-gray-300 leading-relaxed space-y-1">{sec.content.split('\n').map((line, li) => { if (line.startsWith('**') && line.endsWith('**')) return <h4 key={li} className="font-semibold text-white mt-3">{line.replace(/\*\*/g, '')}</h4>; if (line.startsWith('- ')) return <p key={li} className="ml-4 text-gray-400">• {line.replace('- ', '')}</p>; if (line.trim() === '') return <br key={li} />; const wb = line.replace(/\*\*([^*]+)\*\*/g, '<strong class="font-semibold text-white">$1</strong>'); const wc = wb.replace(/`([^`]+)`/g, '<code class="bg-gray-800 px-1 py-0.5 rounded text-red-400 text-xs font-mono">$1</code>'); return <p key={li} className="text-gray-300" dangerouslySetInnerHTML={{ __html: wc }} />; })}</div>{sec.sources.length > 0 && <div className="mt-4 pt-3 border-t border-gray-800/30 flex flex-wrap gap-1.5">{sec.sources.map(s => <span key={s} className="text-[10px] px-2 py-0.5 rounded bg-blue-500/5 text-blue-400 border border-blue-500/10 flex items-center gap-1"><ExternalLink size={8} />{s}</span>)}</div>}</div>)}
      <div className="bg-[#0d0d18] border border-gray-800/40 rounded-xl p-5"><h3 className="text-sm font-semibold text-white mb-3 flex items-center gap-2"><Globe size={14} className="text-blue-400" />All Sources ({result.sources.length})</h3><div className="flex flex-wrap gap-2">{result.sources.map(s => <span key={s} className="text-xs px-3 py-1.5 rounded-lg bg-blue-500/5 border border-blue-500/10 text-blue-400 flex items-center gap-1.5"><ExternalLink size={10} />{s}</span>)}</div></div>
    </div>}
    {!result && !loading && <div className="bg-[#0d0d18] border border-gray-800/40 rounded-xl flex flex-col items-center py-16 text-center animate-slide-up" style={{ animationDelay: '160ms' }}><div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-orange-500/10 to-red-500/10 flex items-center justify-center mb-4 border border-orange-500/15"><Sparkles size={28} className="text-orange-400/40" /></div><p className="text-sm text-gray-500">Enter a security topic for deep multi-source research</p><p className="text-xs text-gray-600 mt-1">Structured analysis with sourced information</p></div>}
  </div>);
}
