import { useState } from 'react';
import { Radar, Search, AlertCircle, AlertTriangle, Shield, ExternalLink, Copy, ChevronDown, Globe, Lock, Target } from 'lucide-react';
import { threatEntries } from '../utils/threatIntel';
import { ThreatEntry } from '../types';
const typeC: Record<string, { bg: string; t: string; b: string }> = { apt: { bg: 'bg-red-500/10', t: 'text-red-400', b: 'border-red-500/20' }, malware: { bg: 'bg-purple-500/10', t: 'text-purple-400', b: 'border-purple-500/20' }, vulnerability: { bg: 'bg-amber-500/10', t: 'text-amber-400', b: 'border-amber-500/20' }, campaign: { bg: 'bg-cyan-500/10', t: 'text-cyan-400', b: 'border-cyan-500/20' }, technique: { bg: 'bg-blue-500/10', t: 'text-blue-400', b: 'border-blue-500/20' } };
const sevC: Record<string, { i: React.ReactNode; t: string; bg: string }> = { critical: { i: <AlertCircle size={14} />, t: 'text-red-400', bg: 'bg-red-500/10' }, high: { i: <AlertTriangle size={14} />, t: 'text-orange-400', bg: 'bg-orange-500/10' }, medium: { i: <AlertTriangle size={14} />, t: 'text-amber-400', bg: 'bg-amber-500/10' }, low: { i: <Shield size={14} />, t: 'text-blue-400', bg: 'bg-blue-500/10' } };
export default function ThreatIntel() {
  const [q, setQ] = useState(''); const [fT, setFT] = useState('all'); const [fS, setFS] = useState('all'); const [sel, setSel] = useState<ThreatEntry | null>(null); const [copiedIOC, setCopiedIOC] = useState<string | null>(null);
  const filtered = threatEntries.filter(t => (!q || t.title.toLowerCase().includes(q.toLowerCase()) || t.description.toLowerCase().includes(q.toLowerCase())) && (fT === 'all' || t.type === fT) && (fS === 'all' || t.severity === fS));
  const copyIOC = (ioc: string) => { navigator.clipboard.writeText(ioc); setCopiedIOC(ioc); setTimeout(() => setCopiedIOC(null), 2000); };
  if (sel) return (<div className="space-y-6 animate-fade-in"><button onClick={() => setSel(null)} className="text-xs text-gray-500 hover:text-gray-300">← Back</button><div className="bg-[#0d0d18] border border-gray-800/40 rounded-xl"><div className="p-6 border-b border-gray-800/30"><div className="flex items-start gap-4"><div className={`p-3 rounded-xl ${sevC[sel.severity].bg}`}>{sevC[sel.severity].i}</div><div><h2 className="text-xl font-bold text-white">{sel.title}</h2><div className="flex items-center gap-2 mt-2 flex-wrap"><span className={`text-xs px-2 py-1 rounded border ${typeC[sel.type].bg} ${typeC[sel.type].t} ${typeC[sel.type].b}`}>{sel.type.toUpperCase()}</span><span className={`text-xs px-2 py-1 rounded ${sevC[sel.severity].bg} ${sevC[sel.severity].t} uppercase font-medium`}>{sel.severity}</span>{sel.mitre && <span className="text-xs text-gray-500 bg-gray-800 px-2 py-1 rounded font-mono">{sel.mitre}</span>}</div></div></div></div>
    <div className="p-6 space-y-6"><div><h3 className="text-sm font-semibold text-white mb-2">Description</h3><p className="text-sm text-gray-400">{sel.description}</p></div>
    {sel.ioc.length > 0 && <div><h3 className="text-sm font-semibold text-white mb-2 flex items-center gap-2"><Lock size={14} className="text-cyan-400" />IOCs</h3><div className="space-y-1.5">{sel.ioc.map((ioc, i) => <div key={i} className="flex items-center justify-between bg-gray-800/20 rounded-lg px-3 py-2 group"><code className="text-xs text-gray-300 font-mono">{ioc}</code><button onClick={() => copyIOC(ioc)} className="text-gray-600 hover:text-cyan-400 opacity-0 group-hover:opacity-100">{copiedIOC === ioc ? <span className="text-[10px] text-emerald-400">Copied!</span> : <Copy size={12} />}</button></div>)}</div></div>}
    <div><h3 className="text-sm font-semibold text-white mb-2 flex items-center gap-2"><Shield size={14} className="text-emerald-400" />Mitigation</h3><div className="space-y-1.5">{sel.mitigation.map((m, i) => <div key={i} className="flex items-start gap-2 p-2 rounded bg-emerald-500/5 border border-emerald-500/10"><span className="text-emerald-400 text-xs mt-0.5">✓</span><p className="text-xs text-gray-300">{m}</p></div>)}</div></div>
    <div><h3 className="text-sm font-semibold text-white mb-2 flex items-center gap-2"><Target size={14} className="text-red-400" />Defense Strategy</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-2">{sel.defenseStrategy.map((s, i) => <div key={i} className="p-3 rounded bg-red-500/5 border border-red-500/10"><p className="text-xs text-gray-300">{s}</p></div>)}</div></div>
    <div><h3 className="text-sm font-semibold text-white mb-2 flex items-center gap-2"><Globe size={14} className="text-blue-400" />Sources</h3><div className="flex flex-wrap gap-2">{sel.sources.map((s, i) => <span key={i} className="text-xs px-2.5 py-1 rounded bg-blue-500/5 border border-blue-500/10 text-blue-400 flex items-center gap-1"><ExternalLink size={10} />{s}</span>)}</div></div>
    </div></div></div>);
  return (<div className="space-y-6 animate-fade-in"><div><h1 className="text-2xl font-bold text-white flex items-center gap-2"><Radar size={24} className="text-amber-400" /> Threat Intelligence</h1><p className="text-gray-400 mt-1 text-sm">Analyze threats with IOCs, MITRE ATT&CK, and defense strategy planning</p></div>
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 animate-slide-up">{[{l:'Total',v:threatEntries.length,i:<Radar size={16} className="text-amber-400"/>,bg:'bg-amber-500/10'},{l:'Critical',v:threatEntries.filter(t=>t.severity==='critical').length,i:<AlertCircle size={16} className="text-red-400"/>,bg:'bg-red-500/10'},{l:'APTs',v:threatEntries.filter(t=>t.type==='apt').length,i:<Globe size={16} className="text-purple-400"/>,bg:'bg-purple-500/10'},{l:'CVEs',v:threatEntries.filter(t=>t.type==='vulnerability').length,i:<Shield size={16} className="text-cyan-400"/>,bg:'bg-cyan-500/10'}].map(s=><div key={s.l} className={`${s.bg} border border-gray-800/40 rounded-xl p-4 flex items-center gap-3`}><div className={`${s.bg} p-2 rounded-lg`}>{s.i}</div><div><p className="text-xl font-bold text-white">{s.v}</p><p className="text-[10px] text-gray-500">{s.l}</p></div></div>)}</div>
    <div className="flex flex-col sm:flex-row gap-3 animate-slide-up" style={{animationDelay:'80ms'}}><div className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search threats, IOCs..." className="w-full pl-9 pr-4 py-2.5 bg-[#0d0d18] border border-gray-800/40 rounded-lg text-sm text-gray-200 placeholder-gray-600 focus:outline-none focus:border-amber-500/50"/></div><div className="relative"><select value={fT} onChange={e=>setFT(e.target.value)} className="appearance-none bg-[#0d0d18] border border-gray-800/40 rounded-lg px-4 py-2.5 text-sm text-gray-200 pr-9"><option value="all">All Types</option><option value="apt">APT</option><option value="malware">Malware</option><option value="vulnerability">CVEs</option><option value="technique">Techniques</option></select><ChevronDown size={14} className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 pointer-events-none"/></div><div className="relative"><select value={fS} onChange={e=>setFS(e.target.value)} className="appearance-none bg-[#0d0d18] border border-gray-800/40 rounded-lg px-4 py-2.5 text-sm text-gray-200 pr-9"><option value="all">All Severity</option><option value="critical">Critical</option><option value="high">High</option></select><ChevronDown size={14} className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 pointer-events-none"/></div></div>
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">{filtered.map((t,i)=>{const tc=typeC[t.type];const sc=sevC[t.severity];return(<button key={t.id} onClick={()=>setSel(t)} className="text-left bg-[#0d0d18] border border-gray-800/40 rounded-xl p-5 hover:border-gray-700/60 transition-all group animate-slide-up" style={{animationDelay:`${i*60}ms`}}><div className="flex items-start justify-between mb-3"><div className="flex items-center gap-2"><span className={`text-xs px-2 py-0.5 rounded border ${tc.bg} ${tc.t} ${tc.b}`}>{t.type.toUpperCase()}</span><span className={`text-xs px-2 py-0.5 rounded ${sc.bg} ${sc.t} uppercase font-medium`}>{t.severity}</span></div><span className="text-[10px] text-gray-600">{t.date}</span></div><h3 className="text-sm font-semibold text-white group-hover:text-amber-400 mb-2">{t.title}</h3><p className="text-xs text-gray-500 line-clamp-2">{t.description}</p>{t.mitre&&<p className="text-[10px] text-gray-600 mt-2 font-mono">{t.mitre}</p>}</button>);})}</div></div>);
}
