import { useState } from 'react';
import { BookOpen, Search, Copy, Download, ExternalLink, ChevronDown, Tag } from 'lucide-react';
import { securityToolTemplates, toolCategories } from '../utils/securityTools';
import { SecurityTool } from '../types';
const catC: Record<string, string> = { 'Web Application': 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20', 'Network': 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20', 'Authentication': 'bg-amber-500/10 text-amber-400 border-amber-500/20', 'Defensive': 'bg-purple-500/10 text-purple-400 border-purple-500/20' };
const diffC: Record<string, string> = { beginner: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20', intermediate: 'bg-amber-500/10 text-amber-400 border-amber-500/20', advanced: 'bg-red-500/10 text-red-400 border-red-500/20' };
export default function ToolLibrary() {
  const [q, setQ] = useState(''); const [cat, setCat] = useState('All'); const [sel, setSel] = useState<SecurityTool | null>(null); const [copied, setCopied] = useState<string | null>(null); const [tab, setTab] = useState<'code' | 'tests' | 'docs'>('code');
  const filtered = securityToolTemplates.filter(t => (!q || t.name.toLowerCase().includes(q.toLowerCase()) || t.description.toLowerCase().includes(q.toLowerCase())) && (cat === 'All' || t.category === cat));
  const copy = (id: string, text: string) => { navigator.clipboard.writeText(text); setCopied(id); setTimeout(() => setCopied(null), 2000); };
  const dl = (t: SecurityTool) => { const ext: Record<string, string> = { Python: 'py', JavaScript: 'js', Bash: 'sh', Go: 'go' }; const c = tab === 'code' ? t.code : tab === 'tests' ? t.tests : t.docs; const b = new Blob([c], { type: 'text/plain' }); const a = document.createElement('a'); a.href = URL.createObjectURL(b); a.download = `${t.id}${tab !== 'code' ? '_' + tab : ''}.${ext[t.language] || 'txt'}`; a.click(); };
  if (sel) return (<div className="space-y-4 animate-fade-in"><button onClick={() => setSel(null)} className="text-xs text-gray-500 hover:text-gray-300">← Back</button><div className="bg-[#0d0d18] border border-gray-800/40 rounded-xl overflow-hidden"><div className="p-5 border-b border-gray-800/30"><h2 className="text-xl font-bold text-white">{sel.name}</h2><p className="text-sm text-gray-400 mt-1">{sel.description}</p><div className="flex items-center gap-2 mt-3 flex-wrap"><span className={`text-xs px-2 py-1 rounded border ${catC[sel.category] || 'bg-gray-500/10 text-gray-400 border-gray-500/20'}`}>{sel.category}</span><span className="text-xs px-2 py-1 rounded bg-gray-800 text-gray-300 border border-gray-700">{sel.language}</span><span className={`text-xs px-2 py-1 rounded border ${diffC[sel.difficulty]}`}>{sel.difficulty}</span></div></div>
    <div className="flex gap-1 px-5 pt-3">{(['code', 'tests', 'docs'] as const).map(t => <button key={t} onClick={() => setTab(t)} className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-all ${tab === t ? 'bg-red-500/15 text-red-400 border border-red-500/20' : 'text-gray-500 border border-transparent'}`}>{t.toUpperCase()}</button>)}</div>
    <div className="p-5 max-h-[500px] overflow-y-auto"><pre className="text-xs font-mono text-gray-300 whitespace-pre-wrap">{tab === 'code' ? sel.code : tab === 'tests' ? sel.tests : sel.docs}</pre></div></div></div>);
  return (<div className="space-y-6 animate-fade-in"><div><h1 className="text-2xl font-bold text-white flex items-center gap-2"><BookOpen size={24} className="text-purple-400" /> Tool Library</h1><p className="text-gray-400 mt-1 text-sm">Free, open-source tools with tests and docs</p></div>
    <div className="flex gap-3 animate-slide-up"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" /><input type="text" value={q} onChange={e => setQ(e.target.value)} placeholder="Search..." className="w-full pl-9 pr-4 py-2.5 bg-[#0d0d18] border border-gray-800/40 rounded-lg text-sm text-gray-200 placeholder-gray-600 focus:outline-none focus:border-red-500/50" /></div><div className="relative"><select value={cat} onChange={e => setCat(e.target.value)} className="appearance-none bg-[#0d0d18] border border-gray-800/40 rounded-lg px-4 py-2.5 text-sm text-gray-200 focus:outline-none pr-9">{toolCategories.map(c => <option key={c} value={c}>{c}</option>)}</select><ChevronDown size={14} className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 pointer-events-none" /></div></div>
    <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{filtered.map((t, i) => (
      <div key={t.id} onClick={() => { setSel(t); setTab('code'); }} className="bg-[#0d0d18] border border-gray-800/40 rounded-xl p-5 hover:border-gray-700/60 transition-all cursor-pointer group flex flex-col animate-slide-up" style={{ animationDelay: `${i * 60}ms` }}>
        <div className="flex items-start justify-between mb-3"><span className={`text-xs px-2 py-1 rounded border ${catC[t.category] || 'bg-gray-500/10 text-gray-400 border-gray-500/20'}`}>{t.category}</span><div className="flex gap-1"><span className="text-[10px] px-1.5 py-0.5 rounded bg-gray-800 text-gray-400">{t.language}</span><span className={`text-[10px] px-1.5 py-0.5 rounded border ${diffC[t.difficulty]}`}>{t.difficulty}</span></div></div>
        <h3 className="text-sm font-semibold text-white group-hover:text-red-400 mb-2">{t.name}</h3>
        <p className="text-xs text-gray-500 leading-relaxed flex-1 line-clamp-2">{t.description}</p>
        <div className="flex items-center gap-1.5 mt-3">{t.tags.slice(0, 3).map(x => <span key={x} className="flex items-center gap-0.5 text-[10px] text-gray-500"><Tag size={7} />{x}</span>)}</div>
        <div className="flex items-center gap-3 mt-4 pt-3 border-t border-gray-800/20">
          <button onClick={e => { e.stopPropagation(); copy(t.id, t.code); }} className="flex items-center gap-1 text-xs text-gray-500 hover:text-red-400"><Copy size={10} />{copied === t.id ? 'Copied!' : 'Copy'}</button>
          <button onClick={e => { e.stopPropagation(); dl(t); }} className="flex items-center gap-1 text-xs text-gray-500 hover:text-cyan-400"><Download size={10} />Download</button>
          <button className="flex items-center gap-1 text-xs text-gray-500 hover:text-purple-400"><ExternalLink size={10} />View</button>
        </div>
      </div>))}</div></div>);
}
