import { useState } from 'react';
import { GraduationCap, BookOpen, CheckCircle, XCircle, ChevronRight, Award, Clock, Target } from 'lucide-react';
import { trainingModules } from '../utils/trainingData';
import { TrainingModule, TrainingLesson } from '../types';
const catC: Record<string, { bg: string; text: string; border: string }> = { 'security-concepts': { bg: 'bg-red-500/10', text: 'text-red-400', border: 'border-red-500/20' }, 'vulnerability-awareness': { bg: 'bg-amber-500/10', text: 'text-amber-400', border: 'border-amber-500/20' }, 'red-team': { bg: 'bg-purple-500/10', text: 'text-purple-400', border: 'border-purple-500/20' }, 'opsec': { bg: 'bg-cyan-500/10', text: 'text-cyan-400', border: 'border-cyan-500/20' }, 'privacy': { bg: 'bg-emerald-500/10', text: 'text-emerald-400', border: 'border-emerald-500/20' } };
const diffC: Record<string, string> = { beginner: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20', intermediate: 'bg-amber-500/10 text-amber-400 border-amber-500/20', advanced: 'bg-red-500/10 text-red-400 border-red-500/20' };
function fmt(c: string) { return c.split('\n').map((l, i) => { if (l.startsWith('## ')) return <h2 key={i} className="text-lg font-bold text-white mt-5 mb-2">{l.replace('## ', '')}</h2>; if (l.startsWith('```')) return null; if (l.startsWith('- ')) return <p key={i} className="ml-4 text-gray-300 text-sm mt-1">• {l.replace('- ', '')}</p>; if (l.trim() === '') return <br key={i} />; const wc = l.replace(/`([^`]+)`/g, '<code class="bg-gray-800 px-1 py-0.5 rounded text-red-400 text-xs font-mono">$1</code>'); const wb = wc.replace(/\*\*([^*]+)\*\*/g, '<strong class="font-semibold text-white">$1</strong>'); return <p key={i} className="text-gray-300 text-sm leading-relaxed mt-1" dangerouslySetInnerHTML={{ __html: wb }} />; }).filter(Boolean); }
export default function TrainingHub() {
  const [selMod, setSelMod] = useState<TrainingModule | null>(null);
  const [selLesson, setSelLesson] = useState<TrainingLesson | null>(null);
  const [quizMode, setQuizMode] = useState(false);
  const [quizAns, setQuizAns] = useState<Record<number, number>>({});
  const [quizDone, setQuizDone] = useState(false);
  const [completed, setCompleted] = useState<Set<string>>(new Set());
  const [simStep, setSimStep] = useState(0);
  const [simAns, setSimAns] = useState<Record<number, number>>({});
  const [simDone, setSimDone] = useState(false);

  if (selMod) { const cc = catC[selMod.category]; return (
    <div className="space-y-6 animate-fade-in">
      <button onClick={() => { setSelMod(null); setSelLesson(null); }} className="text-xs text-gray-500 hover:text-gray-300">← Back</button>
      <div className="bg-[#0d0d18] border border-gray-800/40 rounded-xl p-6 animate-slide-up">
        <div className="flex items-start gap-4"><div className={`text-3xl p-3 rounded-xl ${cc.bg} ${cc.border} border`}>{selMod.icon}</div><div><h1 className="text-xl font-bold text-white">{selMod.title}</h1><p className="text-sm text-gray-400 mt-1">{selMod.description}</p><div className="flex items-center gap-3 mt-3"><span className={`text-xs px-2 py-1 rounded border ${diffC[selMod.difficulty]}`}>{selMod.difficulty}</span><span className="text-xs text-gray-500 flex items-center gap-1"><Clock size={11} />{selMod.duration}</span><span className="text-xs text-gray-500">{selMod.lessons.length} lessons</span></div></div></div>
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        <div className="space-y-2">{selMod.lessons.map(l => { const active = selLesson?.id === l.id; const done = completed.has(l.id); return <button key={l.id} onClick={() => { setSelLesson(l); setQuizMode(false); setSimStep(0); setSimDone(false); setQuizDone(false); }} className={`w-full text-left flex items-center gap-3 px-4 py-3 rounded-lg transition-all text-sm ${active ? 'bg-gradient-to-r from-red-500/10 to-purple-500/10 border border-red-500/20 text-white' : 'bg-[#0d0d18] border border-gray-800/40 text-gray-400 hover:text-white hover:border-gray-700'}`}>{done ? <CheckCircle size={16} className="text-emerald-400 shrink-0" /> : <div className={`w-4 h-4 rounded-full border-2 shrink-0 ${l.type === 'simulation' ? 'border-purple-500' : 'border-gray-600'}`} />}<span className="truncate">{l.title}</span>{l.type === 'simulation' && <Target size={12} className="text-purple-400 shrink-0 ml-auto" />}<ChevronRight size={14} className="text-gray-600 shrink-0" /></button>; })}</div>
        <div className="lg:col-span-3">
          {selLesson ? (quizMode && selLesson.quiz ? (
            <div className="bg-[#0d0d18] border border-gray-800/40 rounded-xl p-6 animate-fade-in"><h2 className="text-lg font-bold text-white mb-4">Quiz: {selLesson.title}</h2><div className="space-y-5">{selLesson.quiz.map((q, qi) => (<div key={qi} className="space-y-2"><p className="text-sm font-medium text-gray-200">{qi + 1}. {q.question}</p><div className="space-y-1.5">{q.options.map((o, oi) => { const sel = quizAns[qi] === oi; const ok = quizDone && oi === q.correctIndex; const bad = quizDone && sel && oi !== q.correctIndex; return <button key={oi} onClick={() => !quizDone && setQuizAns(p => ({ ...p, [qi]: oi }))} className={`w-full text-left px-4 py-2.5 rounded-lg text-sm border ${ok ? 'bg-emerald-500/10 border-emerald-500/25 text-emerald-400' : bad ? 'bg-red-500/10 border-red-500/25 text-red-400' : sel ? 'bg-purple-500/10 border-purple-500/25 text-purple-300' : 'bg-gray-800/20 border-gray-700/20 text-gray-400'}`}>{o}{ok && <CheckCircle size={14} className="inline ml-2 text-emerald-400" />}{bad && <XCircle size={14} className="inline ml-2 text-red-400" />}</button>; })}</div>{quizDone && <div className={`p-3 rounded-lg text-xs ${quizAns[qi] === q.correctIndex ? 'bg-emerald-500/5 border border-emerald-500/10 text-emerald-400' : 'bg-red-500/5 border border-red-500/10 text-red-400'}`}>{q.explanation}</div>}</div>))}</div>
              <div className="mt-6 flex gap-4">{!quizDone ? <button onClick={() => { setQuizDone(true); setCompleted(p => new Set([...p, selLesson.id])); }} disabled={Object.keys(quizAns).length < (selLesson.quiz?.length || 0)} className="px-5 py-2.5 rounded-lg bg-gradient-to-r from-red-500 to-purple-600 text-white text-sm disabled:from-gray-700 disabled:to-gray-700 disabled:text-gray-500">Submit</button> : <><span className="text-lg font-bold text-emerald-400">Score: {Math.round(selLesson.quiz.filter((q, i) => quizAns[i] === q.correctIndex).length / selLesson.quiz.length * 100)}%</span><button onClick={() => { setQuizMode(false); setQuizDone(false); }} className="px-4 py-2 rounded-lg bg-gray-800 text-gray-300 text-sm">Back</button></>}</div></div>
          ) : selLesson.type === 'simulation' && selLesson.scenario ? (
            <div className="bg-[#0d0d18] border border-gray-800/40 rounded-xl p-6 animate-fade-in">
              <div className="flex items-center gap-2 mb-2"><Target size={18} className="text-purple-400" /><h2 className="text-lg font-bold text-white">{selLesson.scenario.title}</h2></div>
              <p className="text-sm text-gray-400 mb-6">{selLesson.scenario.context}</p>
              {!simDone ? (<div className="space-y-4">
                <div className="flex items-center gap-2 mb-2"><span className="text-xs text-purple-400">Step {simStep + 1}/{selLesson.scenario.steps.length}</span><div className="flex-1 bg-gray-800/40 rounded-full h-1.5"><div className="h-1.5 rounded-full bg-purple-500" style={{ width: `${(simStep / selLesson.scenario.steps.length) * 100}%` }} /></div></div>
                <div className="p-4 rounded-lg bg-purple-500/5 border border-purple-500/15"><p className="text-sm text-gray-300">{selLesson.scenario.steps[simStep].situation}</p></div>
                <p className="text-sm font-medium text-white">{selLesson.scenario.steps[simStep].question}</p>
                <div className="space-y-2">{selLesson.scenario.steps[simStep].options.map((o, oi) => (<button key={oi} onClick={() => setSimAns(p => ({ ...p, [simStep]: oi }))} className={`w-full text-left px-4 py-3 rounded-lg text-sm border ${simAns[simStep] === oi ? 'bg-purple-500/10 border-purple-500/25 text-purple-300' : 'bg-gray-800/20 border-gray-700/20 text-gray-400'}`}>{o}</button>))}</div>
                {simAns[simStep] !== undefined && (<div className={`p-4 rounded-lg text-sm border ${simAns[simStep] === selLesson.scenario.steps[simStep].correctIndex ? 'bg-emerald-500/5 border-emerald-500/15 text-emerald-400' : 'bg-amber-500/5 border-amber-500/15 text-amber-400'}`}><p className="font-medium mb-1">{simAns[simStep] === selLesson.scenario.steps[simStep].correctIndex ? '✓ Correct' : '⚠ Not optimal'}</p><p>{selLesson.scenario.steps[simStep].explanation}</p><p className="mt-2 text-xs text-gray-400 italic">{selLesson.scenario.steps[simStep].consequence}</p></div>)}
                {simAns[simStep] !== undefined && (<button onClick={() => { if (simStep < selLesson.scenario!.steps.length - 1) setSimStep(simStep + 1); else { setSimDone(true); setCompleted(p => new Set([...p, selLesson.id])); } }} className="mt-4 px-5 py-2.5 rounded-lg bg-gradient-to-r from-purple-500 to-red-500 text-white text-sm">{simStep < selLesson.scenario!.steps.length - 1 ? 'Next Step →' : 'Complete'}</button>)}
              </div>) : (<div className="text-center py-8"><div className="w-16 h-16 rounded-full bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center mx-auto mb-4"><CheckCircle size={32} className="text-emerald-400" /></div><h3 className="text-lg font-bold text-white mb-2">Simulation Complete!</h3><p className="text-sm text-gray-400">Score: {Object.entries(simAns).filter(([i, s]) => s === selLesson.scenario!.steps[Number(i)].correctIndex).length}/{selLesson.scenario.steps.length}</p><button onClick={() => { setSimStep(0); setSimAns({}); setSimDone(false); }} className="mt-4 px-4 py-2 rounded-lg bg-gray-800 text-gray-300 text-sm">Retry</button></div>)}
            </div>
          ) : (
            <div className="bg-[#0d0d18] border border-gray-800/40 rounded-xl p-6 animate-fade-in">
              <div className="flex items-center justify-between mb-4"><h2 className="text-lg font-bold text-white">{selLesson.title}</h2>{selLesson.quiz && <button onClick={() => { setQuizMode(true); setQuizAns({}); setQuizDone(false); }} className="px-3 py-1.5 rounded-lg bg-amber-500/10 border border-amber-500/20 text-amber-400 text-xs"><Award size={13} className="inline mr-1" />Quiz</button>}</div>
              <div className="prose-invert max-w-none">{fmt(selLesson.content)}</div>
            </div>
          )) : <div className="bg-[#0d0d18] border border-gray-800/40 rounded-xl flex flex-col items-center justify-center h-64"><GraduationCap size={32} className="text-gray-700 mb-3" /><p className="text-sm text-gray-500">Select a lesson</p></div>}
        </div>
      </div>
    </div>); }
  return (<div className="space-y-6 animate-fade-in"><div><h1 className="text-2xl font-bold text-white flex items-center gap-2"><GraduationCap size={24} className="text-amber-400" /> Training Hub</h1><p className="text-gray-400 mt-1 text-sm">Interactive lessons, quizzes, and red team simulations</p></div>
    <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{trainingModules.map((m, i) => { const cc = catC[m.category]; return <button key={m.id} onClick={() => setSelMod(m)} className="text-left bg-[#0d0d18] border border-gray-800/40 rounded-xl p-5 hover:border-gray-700/60 transition-all group animate-slide-up" style={{ animationDelay: `${i * 80}ms` }}><div className="flex items-start justify-between mb-3"><div className={`text-2xl p-2 rounded-xl ${cc.bg} ${cc.border} border`}>{m.icon}</div><span className={`text-[10px] px-2 py-0.5 rounded border ${diffC[m.difficulty]}`}>{m.difficulty}</span></div><h3 className="text-sm font-semibold text-white group-hover:text-red-400 mb-1">{m.title}</h3><p className="text-xs text-gray-500 line-clamp-2">{m.description}</p><div className="flex items-center gap-3 mt-3 text-[11px] text-gray-500"><span className="flex items-center gap-1"><Clock size={10} />{m.duration}</span><span className="flex items-center gap-1"><BookOpen size={10} />{m.lessons.length}</span>{m.lessons.some(l => l.type === 'simulation') && <span className="text-purple-400 flex items-center gap-1"><Target size={10} />Sim</span>}</div></button>; })}</div></div>);
}
