import { useState } from 'react';
import { HelpCircle, ChevronDown, Flame, Wrench, SearchCode, MessageSquare, GraduationCap, Radar, Microscope, Shield, BookOpen, ExternalLink } from 'lucide-react';
const sections = [
  { id: 'start', title: 'Getting Started', icon: <Flame size={17} className="text-red-400" />, content: '**RedHydra AI** is a free, open-source AI security platform with 5 specialized AI personas, 3 thinking modes, and dynamic response generation.\n\n1. **AI Agent** — 5 personas (Security Assistant, Red Team, Code Expert, Threat Analyst, Blue Team)\n2. **Thinking Modes** — Quick, Deep Think, Deeper Think with reasoning chains\n3. **Browser AI** — Open-source WebLLM where supported, with local fallback\n4. **Tool Generator** — Natural language → code + tests + docs\n5. **Code Analyzer** — Vulnerability detection with PoC examples and CWE refs\n6. **Training Hub** — Interactive lessons, quizzes, red team simulations\n7. **Threat Intel** — IOCs, MITRE ATT&CK, defense strategy planning\n8. **Deep Research** — Multi-source analysis with executive summaries\n9. **Settings** — Local AI status, encrypted memory, and production options' },
  { id: 'agent', title: 'AI Agent Personas', icon: <MessageSquare size={17} className="text-purple-400" />, content: '**5 Specialized Personas:**\n\n- 🛡️ **Security Training Assistant** — General guidance & training\n- 🎯 **Red Team Specialist** — Offensive techniques, OPSEC, exploitation methodology\n- 💻 **Code Security Expert** — Code review, secure coding, SAST/DAST\n- 📡 **Threat Intelligence Analyst** — APT tracking, IOC analysis, CVE research\n- 🏰 **Blue Team Commander** — Defense-in-depth, incident response, hardening\n\n**3 Thinking Modes:**\n- ⚡ **Quick** — Fast, concise answers\n- 🧠 **Deep Think** — Multi-vector analysis with risk scoring\n- 🔬 **Deeper** — Exhaustive analysis with visible reasoning chains\n\n**Live web note:** Static GitHub Pages has no backend search API, so the agent does not fake real-time web results. Use local AI and built-in RedHydra knowledge unless you later add a backend search API.' },
  { id: 'gen', title: 'Tool Generator', icon: <Wrench size={17} className="text-red-400" />, content: 'Generate production-ready tools with:\n- **Code** — Main tool implementation\n- **Tests** — Unit test scaffolding\n- **Documentation** — Usage, detection methods, references\n\nDescribe your tool in natural language. Select type and language. Click Generate.' },
  { id: 'analyzer', title: 'Code Analyzer', icon: <SearchCode size={17} className="text-cyan-400" />, content: 'Paste code (Python/JS/TS) for analysis:\n- Security score 0-100\n- Vulnerabilities with **PoC examples** and **CWE references**\n- Specific fix recommendations\n- Line numbers for each finding' },
  { id: 'training', title: 'Training Hub', icon: <GraduationCap size={17} className="text-amber-400" />, content: '5 modules with interactive lessons, quizzes, and simulations:\n- 🛡️ Security Fundamentals\n- 🐛 OWASP Vulnerability Deep Dive\n- 🎯 Red Team Operations (phishing simulation)\n- 🔐 OPSEC Best Practices\n- 👁️ Privacy-Aware Workflows' },
  { id: 'intel', title: 'Threat Intelligence', icon: <Radar size={17} className="text-amber-400" />, content: 'Real threat data with:\n- IOCs (copy to clipboard for your SIEM)\n- MITRE ATT&CK mapping\n- Mitigation strategies\n- Defense strategy planning\n- Source citations' },
  { id: 'research', title: 'Deep Research', icon: <Microscope size={17} className="text-orange-400" />, content: 'Multi-source research on security topics with:\n- Executive summaries\n- Implementation frameworks\n- Key metrics and outcomes\n- All sources cited (NIST, CISA, OWASP, etc.)' },
  { id: 'about', title: 'About', icon: <Shield size={17} className="text-emerald-400" />, content: '**RedHydra AI v2.1** — MIT License — React + TypeScript + Tailwind\n\n✅ Browser-side AI with 5 personas and 3 thinking depths\n✅ Code + Tests + Docs generation\n✅ Vulnerability detection with PoCs\n✅ Red team simulation exercises\n✅ Threat intelligence with defense strategies\n✅ Deep research with local/offline sourced-style guidance\n✅ OPSEC & privacy-aware workflows\n\nAll tools are for authorized testing and education only.' },
];
export default function UserGuide() {
  const [exp, setExp] = useState<string | null>('start');
  return (<div className="space-y-6 animate-fade-in"><div><h1 className="text-2xl font-bold text-white flex items-center gap-2"><HelpCircle size={24} className="text-emerald-400" /> User Guide</h1><p className="text-gray-400 mt-1 text-sm">Complete documentation</p></div>
    <div className="space-y-2">{sections.map(s => { const isExp = exp === s.id; return <div key={s.id} className={`bg-[#0d0d18] border rounded-xl overflow-hidden transition-all ${isExp ? 'border-gray-700/40' : 'border-gray-800/40'}`}><button onClick={() => setExp(isExp ? null : s.id)} className="w-full flex items-center justify-between px-5 py-4 text-left hover:bg-gray-800/15"><div className="flex items-center gap-3">{s.icon}<span className="text-sm font-semibold text-white">{s.title}</span></div><ChevronDown size={15} className={`text-gray-500 transition-transform duration-300 ${isExp ? 'rotate-180' : ''}`} /></button>{isExp && <div className="px-5 pb-5 animate-fade-in"><div className="pl-8 space-y-1.5">{s.content.split('\n').map((l, i) => { if (l.trim() === '') return <br key={i} />; const wb = l.replace(/\*\*([^*]+)\*\*/g, '<strong class="font-medium text-white">$1</strong>'); return <p key={i} className="text-gray-400 text-sm leading-relaxed" dangerouslySetInnerHTML={{ __html: wb }} />; })}</div></div>}</div>; })}</div>
    <div className="bg-gradient-to-r from-red-500/5 to-cyan-500/5 border border-gray-800/40 rounded-xl p-5"><h2 className="text-sm font-semibold text-white mb-3 flex items-center gap-2"><BookOpen size={15} className="text-red-400" /> Resources</h2><div className="grid grid-cols-1 sm:grid-cols-3 gap-2">{[{ n: 'OWASP', d: 'Security resources' }, { n: 'MITRE ATT&CK', d: 'Adversary tactics' }, { n: 'NIST CSF', d: 'Framework' }, { n: 'CISA', d: 'Gov. alerts' }, { n: 'CVE', d: 'Vulnerability DB' }, { n: 'CWE', d: 'Weakness enum' }].map(r => <div key={r.n} className="flex items-center gap-3 p-3 rounded-lg bg-gray-800/15 border border-gray-800/20"><ExternalLink size={13} className="text-gray-500 shrink-0" /><div><p className="text-xs font-medium text-gray-300">{r.n}</p><p className="text-[10px] text-gray-500">{r.d}</p></div></div>)}</div></div>
  </div>);
}
