import { ThreatEntry } from '../types';
export const threatEntries: ThreatEntry[] = [
  {id:'th-001',title:'APT29 — Cozy Bear Cloud Campaign',type:'apt',severity:'critical',date:'2024-01',description:'Nation-state group targeting cloud infrastructure via password spray, OAuth token abuse, and supply chain compromise.',ioc:['185.225.69.0/24','faviconservices[.]com'],mitigation:['Enforce MFA on all cloud accounts','Monitor OAuth consent grants','Conditional Access policies','Audit cloud permissions'],defenseStrategy:['Zero Trust Architecture','Privileged Identity Management','Cloud workload protection','Identity threat detection'],sources:['MITRE ATT&CK','CISA AA20-352A','Microsoft Threat Intel'],mitre:'T1078, T1190'},
  {id:'th-002',title:'Log4Shell Variants (CVE-2021-44228)',type:'vulnerability',severity:'critical',date:'2024-02',description:'Continued exploitation of Apache Log4j via LDAP/JNDI injection for remote code execution.',ioc:['${jndi:ldap://','${jndi:rmi://','${${lower:j}ndi:'],mitigation:['Update Log4j to 2.17.1+','Block outbound LDAP/RMI','Scan all Java apps'],defenseStrategy:['SBOM management','Automated vuln scanning in CI/CD','Network segmentation','Runtime self-protection'],sources:['NVD','CISA','Apache Advisory'],mitre:'T1190, T1059'},
  {id:'th-003',title:'LockBit 3.0 Ransomware-as-a-Service',type:'malware',severity:'critical',date:'2024-03',description:'Ransomware operation using double extortion: encrypts files and threatens data leaks.',ioc:['Extension: .HLJkNskOq','README.txt ransom note'],mitigation:['Offline encrypted backups','Network segmentation','EDR with behavioral detection'],defenseStrategy:['Incident response plan testing','DLP deployment','Email sandboxing','Threat hunting program'],sources:['CISA AA23-325A','FBI Flash','Europol'],mitre:'T1486, T1490'},
  {id:'th-004',title:'SolarWinds Supply Chain Attack',type:'campaign',severity:'high',date:'2024-01',description:'Supply chain compromise of SolarWinds Orion affecting ~18,000 organizations.',ioc:['avsvmcloud[.]com','SolarWinds.Orion.Core.BusinessLayer.dll'],mitigation:['Audit SolarWinds installations','Supply chain security program','Code signing verification'],defenseStrategy:['Software supply chain verification','Binary analysis of updates','Third-party risk management'],sources:['CISA ED 21-01','FireEye','Microsoft MSTIC'],mitre:'T1195.002'},
  {id:'th-005',title:'AI-Enhanced BEC Campaigns',type:'technique',severity:'high',date:'2024-04',description:'BEC campaigns using AI-generated content for convincing phishing.',ioc:['Domain typosquatting','Reply-to differs from From','Urgent wire transfer requests'],mitigation:['DMARC/DKIM/SPF','Out-of-band verification','Employee training'],defenseStrategy:['AI-based email detection','Executive protection program','Financial control segmentation'],sources:['FBI IC3 Report','Proofpoint'],mitre:'T1566.002'},
  {id:'th-006',title:'MOVEit SQL Injection (CVE-2023-34362)',type:'vulnerability',severity:'critical',date:'2024-02',description:'SQL injection in MOVEit Transfer exploited by Clop group.',ioc:['/api/v1/folders with UNION SELECT','human2.aspx web shell'],mitigation:['Apply patches','Audit for unexpected ASPX files','Reset credentials'],defenseStrategy:['WAF deployment','Database activity monitoring','File integrity monitoring'],sources:['Progress Advisory','CISA AA23-158A'],mitre:'T1190, T1505.003'},
  {id:'th-007',title:'OPSEC for Security Research',type:'technique',severity:'medium',date:'2024-04',description:'Best practices for maintaining OPSEC during security research.',ioc:[],mitigation:['Dedicated research infrastructure','VPN/Tor','VM snapshots','Separate identities'],defenseStrategy:['Legal framework documentation','Responsible disclosure timeline','Encrypted communications'],sources:['OWASP Testing Guide','NIST SP 800-115'],mitre:'N/A'},
];
