import { TrainingModule } from '../types';
export const trainingModules: TrainingModule[] = [
  {id:'security-fundamentals',title:'Security Fundamentals',icon:'🛡️',description:'CIA Triad, threat modeling, defense-in-depth.',category:'security-concepts',difficulty:'beginner',duration:'45 min',lessons:[
    {id:'cia',title:'The CIA Triad',type:'lesson',content:`## CIA Triad\n\n### 🔒 Confidentiality\nEncryption (AES-256, TLS 1.3), access controls (RBAC), data classification.\n\n### ✅ Integrity\nChecksums (SHA-256), digital signatures, audit trails, input validation.\n\n### 🔄 Availability\nRedundancy, DDoS protection, disaster recovery, load balancing.\n\n**Real example:** A bank must keep records private (C), prevent unauthorized changes (I), and ensure 24/7 access (A).`,quiz:[{question:'Which principle does encryption primarily protect?',options:['Integrity','Confidentiality','Availability','All equally'],correctIndex:1,explanation:'Encryption ensures only authorized parties can read data — confidentiality.'}]},
    {id:'stride',title:'Threat Modeling with STRIDE',type:'lesson',content:`## STRIDE Threat Model\n\n- **S**poofing → Authentication\n- **T**ampering → Integrity\n- **R**epudiation → Non-repudiation\n- **I**nformation Disclosure → Confidentiality\n- **D**enial of Service → Availability\n- **E**levation of Privilege → Authorization\n\n### Steps\n1. Diagram the system\n2. Identify threats per component\n3. Assess risk (Likelihood × Impact)\n4. Plan mitigations\n5. Validate and iterate`,quiz:[{question:'What does Tampering violate?',options:['Authentication','Integrity','Confidentiality','Availability'],correctIndex:1,explanation:'Tampering is unauthorized data modification — violates integrity.'}]}]},
  {id:'vuln-awareness',title:'OWASP Vulnerability Deep Dive',icon:'🐛',description:'OWASP Top 10 with real-world examples and PoC development.',category:'vulnerability-awareness',difficulty:'intermediate',duration:'90 min',lessons:[
    {id:'injection',title:'Injection Attacks (A03)',type:'lesson',content:`## Injection\n\n\`\`\`python\n# BAD\nquery = f"SELECT * FROM users WHERE name = '{user_input}'"\n# GOOD\ncursor.execute("SELECT * FROM users WHERE name = %s", (user_input,))\n\`\`\`\n\n**Prevention:** Parameterized queries, input validation, ORM, least privilege, WAF.`,quiz:[{question:'Best defense against SQL injection?',options:['Input validation','Parameterized queries','WAF','Encryption'],correctIndex:1,explanation:'Parameterized queries separate code from data — injection becomes impossible.'}]}]},
  {id:'red-team',title:'Red Team Operations',icon:'🎯',description:'Attack methodology, OPSEC, and adversarial simulation exercises.',category:'red-team',difficulty:'advanced',duration:'120 min',lessons:[
    {id:'recon',title:'Reconnaissance Methodology',type:'lesson',content:`## Reconnaissance\n\n**Passive:** OSINT, WHOIS, DNS, Google dorking, Shodan, social media, job postings\n\n**Active:** Port scanning, service enumeration, web crawling, vulnerability scanning\n\n**OPSEC:** Dedicated infrastructure, VPN/Tor, separate identities, document everything`,quiz:[{question:'Key difference between passive and active recon?',options:['Passive is faster','Passive doesn\'t interact with target','Active is less detectable','No difference'],correctIndex:1,explanation:'Passive recon gathers info without direct interaction with the target.'}]},
    {id:'phishing-sim',title:'🎯 Phishing Simulation',type:'simulation',content:'',scenario:{title:'Phishing Simulation',context:'You are conducting an authorized phishing simulation for Acme Corp (500 employees, Office 365). Goal: test employee awareness while maintaining OPSEC.',steps:[
      {situation:'You need to register a domain for the campaign.',question:'Which domain strategy is best?',options:['acme-security-update.com','Typosquat: acrne.com','Unrelated professional domain: sharepoint-docs.com','Free subdomain service'],correctIndex:2,explanation:'Unrelated professional domain avoids trademark issues and looks realistic.',consequence:'sharepoint-docs.com blends with business comms without legal flags.'},
      {situation:'Crafting the email for the finance department.',question:'Which approach is most realistic?',options:['URGENT: Account deleted in 24h!','Q4 Budget Review — Action Required','You won a $500 gift card!','IT: Password reset immediately'],correctIndex:1,explanation:'Contextually relevant emails (budget for finance) have highest click rates.',consequence:'Finance regularly handles budget docs — realistic test scenario.'},
      {situation:'23% of employees clicked the link. What next?',question:'Most important next step?',options:['Report 23% to management','Targeted training for clickers','Remediate the email system','Send follow-up test tomorrow'],correctIndex:1,explanation:'Targeted training is the primary value of phishing simulations — education, not punishment.',consequence:'Red team exercises should always result in improved defensive posture.'},
    ]}}]},
  {id:'opsec',title:'OPSEC Best Practices',icon:'🔐',description:'Operational security: data handling, communications, identity management.',category:'opsec',difficulty:'intermediate',duration:'60 min',lessons:[
    {id:'opsec-core',title:'OPSEC Core Principles',type:'lesson',content:`## 5-Step OPSEC Process\n1. Identify Critical Information\n2. Analyze Threats\n3. Analyze Vulnerabilities\n4. Assess Risk\n5. Apply Countermeasures\n\n### Digital OPSEC Checklist\n- Unique passwords + password manager\n- MFA on ALL accounts (hardware keys preferred)\n- Encrypted comms (Signal, ProtonMail)\n- Separate personal/work identities\n- VPN/Tor for sensitive browsing\n- Regular digital footprint audit\n- Metadata awareness in documents`,quiz:[{question:'First step in OPSEC?',options:['Analyze threats','Apply countermeasures','Identify critical information','Assess vulnerabilities'],correctIndex:2,explanation:'You must first identify what needs protection.'}]}]},
  {id:'privacy',title:'Privacy-Aware Workflows',icon:'👁️',description:'Privacy by design, data minimization, GDPR/CCPA compliance.',category:'privacy',difficulty:'intermediate',duration:'75 min',lessons:[
    {id:'privacy-design',title:'Privacy by Design',type:'lesson',content:`## 7 Principles\n1. Proactive, not reactive\n2. Privacy as default\n3. Embedded privacy\n4. Full functionality\n5. End-to-end security\n6. Visibility & transparency\n7. Respect for user privacy\n\n### Data Minimization\n\`\`\`python\n# BAD\nuser = {'name':name,'email':email,'ssn':ssn}\n# GOOD\nuser = {'email':email,'hashed_password':hash(pw)}\n\`\`\``,quiz:[{question:'What is data minimization?',options:['Minimal database storage','Collecting only necessary data','Deleting data frequently','Compressing data'],correctIndex:1,explanation:'Collect only the personal data strictly necessary.'}]}]},
];
